"""initial_migration

Revision ID: 8ce1648867f1
Revises: 
Create Date: 2025-01-15 18:32:35.897064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ce1648867f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_index('name')
        batch_op.drop_index('unique_name_date')
        batch_op.create_index(batch_op.f('ix_market_indices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_indices_name'), ['name'], unique=False)
        batch_op.create_unique_constraint('uix_market_indices_name_date', ['name', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.drop_constraint('uix_market_indices_name_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_market_indices_name'))
        batch_op.drop_index(batch_op.f('ix_market_indices_date'))
        batch_op.create_index('unique_name_date', ['name', 'date'], unique=True)
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
