"""recreate market indices table

Revision ID: fa4a036a885e
Revises: 
Create Date: 2025-01-02 17:37:26.095754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4a036a885e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_value', sa.Float(), nullable=True),
    sa.Column('high_value', sa.Float(), nullable=True),
    sa.Column('low_value', sa.Float(), nullable=True),
    sa.Column('close_value', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'date', name='unique_name_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_indices')
    # ### end Alembic commands ###
